# Generated by Django 5.2.7 on 2025-12-06 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0003_topic_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='media_file',
            field=models.FileField(blank=True, null=True, upload_to='entry_media/'),
        ),
    ]
